logging:
  config: C:\\sefaz\\gitlab\\LeitorJDBC-SpringBatch\\config\\log\\log4j.xml
  level:
    org:
      springframework:
        batch:
          item:
            database: DEBUG
rest:
  api:
    url: http://localhost:8080/teste/